[rime-ice]
src.git = "https://github.com/iDvel/rime-ice"
fetch.github = "iDvel/rime-ice"

[librime-lua]
src.git = "https://github.com/hchunhui/librime-lua"
fetch.github = "hchunhui/librime-lua"

[iosevka-zt]
src.github = "zzzsyyy/Iosevka"
fetch.url = "https://github.com/zzzsyyy/Iosevka/releases/download/v$ver/Iosevka-$ver.tar.xz"
src.prefix = "v"

[plangothic]
src.github = "Fitzgerald-Porthmouth-Koenigsegg/Plangothic"
fetch.github = "Fitzgerald-Porthmouth-Koenigsegg/Plangothic"

[firefox-gnome-theme]
src.git = "https://github.com/rafaelmardojai/firefox-gnome-theme"
src.branch = "beta"
fetch.github = "rafaelmardojai/firefox-gnome-theme"

[lxgw-wenkai-screen]
src.github = "lxgw/LxgwWenKai-Screen"
fetch.url = "https://github.com/lxgw/LxgwWenKai-Screen/releases/download/$ver/LXGWWenKaiScreen.ttf"

[gnome-shell-extension-quake-mode]
src.git = "https://github.com/repsac-by/gnome-shell-extension-quake-mode"
fetch.github = "repsac-by/gnome-shell-extension-quake-mode"

[q]
src.github = "natesales/q"
fetch.github = "natesales/q"

[clash-verge-rev]
src.github = "clash-verge-rev/clash-verge-rev"
fetch.url = "https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v$ver/clash-verge_$ver_amd64.deb"
src.prefix = "v"
