[rime-ice]
src.git = "https://github.com/iDvel/rime-ice"
fetch.github = "iDvel/rime-ice"

[librime-lua]
src.git = "https://github.com/hchunhui/librime-lua"
fetch.github = "hchunhui/librime-lua"

[iosevka-zt]
src.github = "zzzsyyy/Iosevka"
fetch.url = "https://github.com/zzzsyyy/Iosevka/releases/download/v$ver/Iosevka-$ver.tar.xz"
src.prefix = "v"


