# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/813df0c9-5773-4f1b-b1fa-0412524f6c60";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" ];
    };

  fileSystems."/etc" =
    { device = "/dev/disk/by-uuid/813df0c9-5773-4f1b-b1fa-0412524f6c60";
      fsType = "btrfs";
      options = [ "subvol=@etc" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/813df0c9-5773-4f1b-b1fa-0412524f6c60";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=sztd:3" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/813df0c9-5773-4f1b-b1fa-0412524f6c60";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/813df0c9-5773-4f1b-b1fa-0412524f6c60";
      fsType = "btrfs";
      options = [ "subvol=@logs" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/813df0c9-5773-4f1b-b1fa-0412524f6c60";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3DE3-B79C";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
