# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "0f8ba203d475587f477e7ae12661bd8459e225b7";
    src = fetchFromGitHub {
      owner = "rafaelmardojai";
      repo = "firefox-gnome-theme";
      rev = "0f8ba203d475587f477e7ae12661bd8459e225b7";
      fetchSubmodules = false;
      sha256 = "sha256-r0gN2brVWA351zwMV0Flmlcd6SGMvYqFbvC3DfKFM8Y=";
    };
    date = "2026-04-13";
  };
  iosevka-zt = {
    pname = "iosevka-zt";
    version = "34.2.1";
    src = fetchurl {
      url = "https://github.com/zzzsyyy/Iosevka/releases/download/v34.2.1/Iosevka-34.2.1.txz";
      sha256 = "sha256-MRkFUXcuME1vAWcJjS+uROqv96ioh3PCodWXZrW7nUY=";
    };
  };
  librime-lua = {
    pname = "librime-lua";
    version = "68f9c364a2d25a04c7d4794981d7c796b05ab627";
    src = fetchFromGitHub {
      owner = "hchunhui";
      repo = "librime-lua";
      rev = "68f9c364a2d25a04c7d4794981d7c796b05ab627";
      fetchSubmodules = false;
      sha256 = "sha256-m7/qXdIlMMHscDDcFmusNuOR0cuzPpDQdprqRci8qZw=";
    };
    date = "2025-07-07";
  };
  lxgw-wenkai-screen = {
    pname = "lxgw-wenkai-screen";
    version = "v1.522";
    src = fetchurl {
      url = "https://github.com/lxgw/LxgwWenKai-Screen/releases/download/v1.522/LXGWWenKaiScreen.ttf";
      sha256 = "sha256-zRpvo5xOpC/Y9OKJlFeJsOUQz3AWQ1ZA+Ik82tmyIPM=";
    };
  };
  plangothic = {
    pname = "plangothic";
    version = "V2.9.5792";
    src = fetchFromGitHub {
      owner = "Fitzgerald-Porthmouth-Koenigsegg";
      repo = "Plangothic-Project";
      rev = "V2.9.5792";
      fetchSubmodules = false;
      sha256 = "sha256-Ftm5ut34Tinqs3NKiGTNvZdm/wjjnPf+AHVinT/qb/o=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "2bd2983c6c74ea49b3a013f150ade7f3b8a27515";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "2bd2983c6c74ea49b3a013f150ade7f3b8a27515";
      fetchSubmodules = false;
      sha256 = "sha256-VRMaa5WY7nqIFI6x3lA2PoEFwdUBPGGOl3k4ThSz4RE=";
    };
    date = "2026-04-14";
  };
}
