# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "91ca1f82d717b02ceb03a3f423cbe8082ebbb26d";
    src = fetchFromGitHub {
      owner = "rafaelmardojai";
      repo = "firefox-gnome-theme";
      rev = "91ca1f82d717b02ceb03a3f423cbe8082ebbb26d";
      fetchSubmodules = false;
      sha256 = "sha256-S79Hqn2EtSxU4kp99t8tRschSifWD4p/51++0xNWUxw=";
    };
    date = "2025-01-14";
  };
  iosevka-zt = {
    pname = "iosevka-zt";
    version = "32.3.0";
    src = fetchurl {
      url = "https://github.com/zzzsyyy/Iosevka/releases/download/v32.3.0/Iosevka-32.3.0.txz";
      sha256 = "sha256-Rb7Ako8oKhFeY7WQ/uqytsnON+vC4VyQK/EDGBHqSUw=";
    };
  };
  librime-lua = {
    pname = "librime-lua";
    version = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
    src = fetchFromGitHub {
      owner = "hchunhui";
      repo = "librime-lua";
      rev = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
      fetchSubmodules = false;
      sha256 = "sha256-zx0F41szn5qlc2MNjt1vizLIsIFQ67fp5cb8U8UUgtY=";
    };
    date = "2024-12-21";
  };
  lxgw-wenkai-screen = {
    pname = "lxgw-wenkai-screen";
    version = "v1.510";
    src = fetchurl {
      url = "https://github.com/lxgw/LxgwWenKai-Screen/releases/download/v1.510/LXGWWenKaiScreen.ttf";
      sha256 = "sha256-JAU87Jb3gqS1mXYprWKYt5xnzMVlZR992PNmsqnTF3U=";
    };
  };
  plangothic = {
    pname = "plangothic";
    version = "V1.9.5769";
    src = fetchFromGitHub {
      owner = "Fitzgerald-Porthmouth-Koenigsegg";
      repo = "Plangothic-Project";
      rev = "V1.9.5769";
      fetchSubmodules = false;
      sha256 = "sha256-jN4OQQL1tkwDpWyk43h75V+7lT1AfiaIRnAgVOQA0rs=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "2a2bb24367ba9948c840fec599710006dcb1e9ca";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "2a2bb24367ba9948c840fec599710006dcb1e9ca";
      fetchSubmodules = false;
      sha256 = "sha256-vB1dXAiFNMAGywq42Waiyhf7ctAM3Vp+/e5y1ntm++c=";
    };
    date = "2025-01-24";
  };
}
