name: lint
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  check:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with: 
          extra_nix_config: |
            extra-experimental-features = nix-command flakes pipe-operators
      - name: Check
        run: nix flake check
      - name: Show
        run: nix flake show
